blank_issues_enabled: false
contact_links:
    - name: Request a feature
      url: https://github.com/produpress/laravel-actito/issues/new
      about: Share ideas for new features
    - name: Report a security issue
      url: https://github.com/produpress/laravel-actito/security/policy
      about: Learn how to notify us for sensitive bugs
    - name: Report a bug
      url: https://github.com/produpress/laravel-actito/issues/new
      about: Report a reproducable bug
